# Posts
GET https://wp-next-demo.armyofbees.net/wp-json/wp/v2/posts

###

# Posts -- titles & slug only, see https://core.trac.wordpress.org/changeset/41744
GET https://wp-next-demo.armyofbees.net/wp-json/wp/v2/posts?_fields=title,slug

###

# Single Post
GET https://wp-next-demo.armyofbees.net/wp-json/wp/v2/posts?slug=hello-world

###

# HTTP AUTH
http://hiveflex:buzz123123@hive-flex.armyofbees.net/wp-json/wp/v2/posts
